### ISSUE TITLE
why cant this simple function works? 

### ISSUE THREAD

**Issue by aanataliya** [VadneyK/coding-challenges#1]
This gives correct result Yes or No.

Or Am I missing something?

def reachTheEnd(grid, maxTime):
    exptectedTime = ((len(grid)-1) + (len(grid[0])-1))
    print(exptectedTime)
    if(exptectedTime<=maxTime):
        return "Yes"
    else:
         return "No"
    

time=5
grid = ['..##','#.##','#...','###.']
res=reachTheEnd(grid,time)
print (res)

**Comment by VadneyK** [comment]
I'm not sure how this relates to my repo. Please ask chatGPT
